---
# This is a basic workflow that run a simple testexecute batch routine
name: BasicWorkflow
run-name: ${{ github.actor }} is learning GitHub Actions

# Controls when the workflow will run
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
# Allows you to run this workflow manually from the actions tab
    workflow_dispatch:
# Basic job to execute a simple batch routine that runs tests via testexecute
jobs:
  build:
      runs-on: self-hosted
  steps: 
  - name:Run a batch file to trigger TestComplete Tests
  working-directory: C:\TestRunner
  run: GitHub_Batch.bat
