---
# This is a basic workflow that run a simple testexecute batch routine
name: BasicWorkflow
run-name: ${{ github.actor }} is learning GitHub Actions

# Controls when the workflow will run
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
        
# Allows you to run this workflow manually from the actions tab
    workflow_dispatch:
    
# Basic job to execute a simple batch routine that runs tests via testexecute
jobs:
  BasicWorkflow:
      runs-on: self-hosted
      steps: 
        - name: BatchJobRun
          working-directory: C:\TestRunner
          run: C:\TestRunner\GitHub_Batch.bat
