name: TestExecuteSimpleTest
on:
workflow_dispatch:
jobs:
  build:
    runs-on:self-hosted
    steps:
      - name: run a batch file to trigger testcomplete tests via testexecute
      - working-directory: c:\testrunner
      - run: ./GitHub_Batch.bat
