name: TestExecute Simple Test
run-name: TestExecute run from GitHub Action (${{ github.actor }})
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
    -name: Run a batch file to run TestComplete test via TestExecute
     working-directory:C:\TestRunner
     run:./GitHub_Batch.bat
