name: Random Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps: 
     run: C:\TestRunner\GITHUB_Batch.bat
